### ISSUE TITLE
SAIGE fails with LOCO = TRUE in fitNULLGLMM

### ISSUE THREAD

**Issue by Ojami** [weizhouUMICH/SAIGE#162]
Hi Wei,

I've came across an error with LOCO flag as TRUE, which I couldn't figure out the source. Here is my code (SAIGE version 0.36.3.2):
```
covarColList <- "cov1,cov2,cov3,cov4,cov5,cov6,cov7,cov8,cov9,cov10,cov11,cov12,cov13,cov14,cov15"
covars <- strsplit(covarColList,",")[[1]]
fitNULLGLMM(plinkFile = "grm.kinship.chr1-22", phenoFile = "phenocov.txt", phenoCol = "y",traitType = "quantitative", covarColList = covars, sampleIDColinphenoFile = "IID", nThreads = 35, memoryChunk = 2, LOCO = TRUE,outputPrefix = "step1_nullmodel", invNormalize = FALSE, relatednessCutoff = 0.125,minCovariateCount=1)
```

And error (removed some extra lines for shortness!):

> "Markers in the Plink file with MAF >=  0.01  will be used to construct GRM
> 35  threads are set to be used  
> leave-one-chromosome-out is activated! Note this option will only be applied to autosomal variants
> chromosomeStartIndexVec:  0 7670 14934 21181 27087 32832 38100 43277 47980 52360 57158 61619 66044 69474 72601 75669 79061 82290 85379 87795 90476 92011 
> chromosomeEndIndexVec:  7669 14933 21180 27086 32831 38099 43276 47979 52359 57157 61618 66043 69473 72600 75668 79060 82289 85378 87794 90475 92010 93510 
> 368813  samples have genotypes
> formula is  y~cov1+cov2+cov3+cov4+cov5+cov6+cov7+cov8+cov9+cov10+cov11+cov12+cov13+cov14+cov15 
> 3559  samples have non-missing phenotypes
> 365254  samples in geno file do not have phenotypes
> 3559  samples will be used for analysis
> qr transformation has been performed on covariates
> colnames(data.new) is  Y minus1 cov1 cov2 cov3 cov4 cov5 cov6 cov7 cov8 cov9 cov10 cov11 cov12 cov13 cov14 cov15 
> out.transform$Param.transform$qrr:  16 16 
> y  is a quantitative trait
> glm:
> 
> Call:  glm(formula = formula.new, family = gaussian(link = ""identity""), 
>     data = data.new)
> 
> Coefficients:
>     minus1        cov1        cov2        cov3        cov4        cov5  
> -0.0002928   0.0876028  -0.1649540   0.4091983  -0.0274606   0.0116576  
>       cov6        cov7        cov8        cov9       cov10       cov11  
> -0.0261172  -0.0132736   0.0253696   0.0101351  -0.0045302  -0.0082236  
>      cov12       cov13       cov14       cov15  
> -0.0218372   0.0048490  -0.0009807   0.0114592  
> 
> Degrees of Freedom: 3559 Total (i.e. Null);  3543 Residual
> Null Deviance:	    3557 
> Residual Deviance: 2825 	AIC: 9312
> Start fitting the NULL GLMM
>    user  system elapsed 
>   2.750   0.671   2.412 
> [1] ""Start reading genotype plink file here""
> nbyte: 92204
> nbyte: 890
> reserve: 83411816
> 
> M: 93511, N: 368813
> size of genoVecofPointers: 5
> setgeno mark1
> setgeno mark2
> 92763 markers with MAF >= 0.01 are used for GRM.
> setgeno mark5
> setgeno mark6
> time: 135312
> [1] ""Genotype reading is done""
> Fixed-effect coefficients:
>        minus1          cov1          cov2          cov3          cov4 
> -0.0002927601  0.0876028279 -0.1649539600  0.4091983314 -0.0274606289 
>          cov5          cov6          cov7          cov8          cov9 
>  0.0116575846 -0.0261172177 -0.0132736050  0.0253695513  0.0101351017 
>         cov10         cov11         cov12         cov13         cov14 
> -0.0045302214 -0.0082235696 -0.0218372299  0.0048489555 -0.0009807100 
>         cov15 
>  0.0114591567 
> initial tau is  1 0 
> iGet_Coef:  1 
> iter from getPCG1ofSigmaAndVector 1
> Tau:
> [1] 1 0
> Fixed-effect coefficients:
>                [,1]
>  [1,] -0.0002927577
>  [2,]  0.0876030773
>  [3,] -0.1649536937
>  [4,]  0.4091981053
>  [5,] -0.0274606720
>  [6,]  0.0116575826
>  [7,] -0.0261172466
>  [8,] -0.0132735725
>  [9,]  0.0253695734
> [10,]  0.0101351039
> [11,] -0.0045302231
> [12,] -0.0082235578
> [13,] -0.0218372028
> [14,]  0.0048489473
> [15,] -0.0009807107
> [16,]  0.0114591951
> iter from getPCG1ofSigmaAndVector 1
> Variance component estimates:
> [1] 0.7985619 0.0000000
> 
> Iteration  1 :
> iGet_Coef:  1 
> iter from getPCG1ofSigmaAndVector 1
> Tau:
> [1] 0.7985619 0.0000000
> Fixed-effect coefficients:
>                [,1]
>  [1,] -0.0002927574
>  [2,]  0.0876021385
>  [3,] -0.1649542153
>  [4,]  0.4091987312
>  [5,] -0.0274605714
>  [6,]  0.0116575761
>  [7,] -0.0261172745
>  [8,] -0.0132735949
>  [9,]  0.0253696050
> [10,]  0.0101351114
> [11,] -0.0045302380
> [12,] -0.0082235876
> [13,] -0.0218372196
> [14,]  0.0048489538
> [15,] -0.0009807006
> [16,]  0.0114591615
> iter from getPCG1ofSigmaAndVector 1
> Variance component estimates:
> [1] 0.6907606 0.1064517
> Fixed-effect coefficients:
>                [,1]
>  [1,] -0.0002927574
>  [2,]  0.0876021385
>  [3,] -0.1649542153
>  [4,]  0.4091987312
>  [5,] -0.0274605714
>  [6,]  0.0116575761
>  [7,] -0.0261172745
>  [8,] -0.0132735949
>  [9,]  0.0253696050
> [10,]  0.0101351114
> [11,] -0.0045302380
> [12,] -0.0082235876
> [13,] -0.0218372196
> [14,]  0.0048489538
> [15,] -0.0009807006
> [16,]  0.0114591615
> 
> Iteration  2 :
> iGet_Coef:  1 
> iter from getPCG1ofSigmaAndVector 3
> Tau:
> [1] 0.6907606 0.1064517
> Fixed-effect coefficients:
>                [,1]
>  [1,] -0.0002928023
>  [2,]  0.0873517022
>  [3,] -0.1652794331
>  [4,]  0.4092987478
>  [5,] -0.0267812815
>  [6,]  0.0110542960
>  [7,] -0.0264684521
>  [8,] -0.0129073318
>  [9,]  0.0257291794
> [10,]  0.0103451051
> [11,] -0.0047503645
> [12,] -0.0080965329
> [13,] -0.0218286999
> [14,]  0.0057741804
> [15,] -0.0011671382
> [16,]  0.0113251014
> iter from getPCG1ofSigmaAndVector 3
> Variance component estimates:
> [1] 0.6926882 0.1051411
> Fixed-effect coefficients:
>                [,1]
>  [1,] -0.0002928023
>  [2,]  0.0873517022
>  [3,] -0.1652794331
>  [4,]  0.4092987478
>  [5,] -0.0267812815
>  [6,]  0.0110542960
>  [7,] -0.0264684521
>  [8,] -0.0129073318
>  [9,]  0.0257291794
> [10,]  0.0103451051
> [11,] -0.0047503645
> [12,] -0.0080965329
> [13,] -0.0218286999
> [14,]  0.0057741804
> [15,] -0.0011671382
> [16,]  0.0113251014
> 
> Final  0.6926882 0.1051411 :
> iGet_Coef:  1 
> iter from getPCG1ofSigmaAndVector 3
> Tau:
> [1] 0.6926882 0.1051411
> Fixed-effect coefficients:
>                [,1]
>  [1,] -0.0002927947
>  [2,]  0.0873548388
>  [3,] -0.1652752161
>  [4,]  0.4092980921
>  [5,] -0.0267900173
>  [6,]  0.0110618630
>  [7,] -0.0264640432
>  [8,] -0.0129122417
>  [9,]  0.0257245488
> [10,]  0.0103426538
> [11,] -0.0047472403
> [12,] -0.0080980808
> [13,] -0.0218285732
> [14,]  0.0057625794
> [15,] -0.0011647915
> [16,]  0.0113268783
> iGet_Coef:  1 
> iter from getPCG1ofSigmaAndVector 1
> 
> warning: inv_sympd(): given matrix is not symmetric
> 
> error: inv_sympd(): matrix is singular or not positive definite
> 
> error: pinv(): svd failed
> Error in getCoefficients_LOCO(Y, X, W, tau, maxiter = maxiterPCG, tol = tolPCG) : 
>   pinv(): svd failed
> Calls: fitNULLGLMM ... glmmkin.ai_PCG_Rcpp_Quantitative -> Get_Coef_LOCO -> getCoefficients_LOCO
> Timing stopped at: 527.2 2.953 147.4
> Execution halted"

I also want to mention the followings:

1. There is no perfect separation in my test.
2. The error is independent of binary/continuous trait: tested for 1 binary and 2 continuous traits of different sizes.
3. Two different sets of markers were tested for GRM.
4. Different combination of covariates was tested (using 1, 3 or all of them).

I appreciate if you could help me with this.

Best/Oveis

**Comment by weizhouUMICH** [comment]
Hi Oveis, 

Can you please have a check to see if there any duplicated samples, who have the same covariates phenotype and genotypes, in the data? 

Thanks,
Wei

**Comment by Ojami** [comment]
Hi Wei,

I just checked it. There is no duplicated samples, or samples with same covariates/phenotype. Additionally, there is no variant duplicate in markers (.bim file).

Thanks,
Oveis

**Comment by weizhouUMICH** [comment]
Hi Oveis, 

Thanks for your quick reply. Just found a bug that can potentially cause the error: The number of markers that was used for division when LOCO =T was larger than it should be.  I've fixed it in 0.36.4.1. 
Can you please have a try? 

Thanks,
Wei

**Comment by Ojami** [comment]
Hi Wei,

Unfortunately, I'm still getting the same error (version 0.36.4.1)

Thanks,
Oveis

**Comment by Ojami** [comment]
Dear Wei,

Did you have time to take a look at the error? 

Thanks
Best/Oveis

**Comment by weizhouUMICH** [comment]
Dear Oveis,

So sorry for the late reply. I will debug using the UKBB data
tomorrow. Thank you for your patience.

Wei

**Comment by weizhouUMICH** [comment]
Dear Oveis, 
Thank you for your patience. I've updated a version to 0.36.5, which I've tested on the UKBB data with LOCO=TRUE. Please give it a try. 

Thanks!
Wei

**Comment by Ojami** [comment]
Dear Wei,

Thanks for your effort on the update. It fixed the issue! 👍 

Best/Oveis
